Transform: AWS::Serverless-2016-10-31

Parameters:

  Email:
    Type: String

Resources:

  Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-${AWS::Region}
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
                - lambda.amazonaws.com
                - states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: admin
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "*"
                Resource: "*"

  Topic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Ref AWS::StackName
      Subscription:
        - Protocol: email
          Endpoint: !Ref Email

  Bucket:
    Type: AWS::S3::Bucket

  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref AWS::StackName
      Runtime: python3.8
      CodeUri: ./stream_function
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Timeout: 60
      Role: !Sub ${Role.Arn}
      Environment:
        Variables:
          BUCKET: !Ref Bucket

  StateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Ref AWS::StackName
      Role: !Sub ${Role.Arn}
      Definition:
        StartAt: Stream
        States:
          Stream:
            Type: Task
            Resource: !Sub ${Function.Arn}
            ResultPath: $.stream
            Catch:
              - ErrorEquals: [States.ALL]
                Next: Email
            Next: Stream
          Email:
            Type: Task
            Resource: arn:aws:states:::sns:publish
            Parameters:
              TopicArn: !Ref Topic
              Subject: !Ref AWS::StackName
              Message.$: $.Cause
            End: True

  Streaming:
    Type: AWS::Glue::Job
    Properties:
      Name: !Ref AWS::StackName
      GlueVersion: 3.0
      MaxCapacity: 2
      MaxRetries: 0
      Role: !Sub ${Role.Arn}
      Timeout: 15
      ExecutionProperty:
        MaxConcurrentRuns: 1
      Command:
        Name: gluestreaming
        PythonVersion: 3
        ScriptLocation: !Sub s3://${Bucket}/infra-artifacts/streaming_job/glue_script.py
      DefaultArguments:
        --enable-glue-datacatalog: true
        --job-bookmark-option: job-bookmark-enable
        --BUCKET: !Ref Bucket

Outputs:

  BucketName:
    Value: !Ref Bucket