Transform: AWS::Serverless-2016-10-31

Resources:

  Bucket:
    Type: AWS::S3::Bucket

  Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./stream_function
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          BUCKET: !Ref Bucket

  StateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Definition:
        StartAt: Stream
        States:
          Stream:
            Type: Task
            Resource: !Sub ${Function.Arn}
