Transform: AWS::Serverless-2016-10-31

Resources:

  Bucket:
    Type: AWS::S3::Bucket

  StreamFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./stream_function
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          BUCKET: !Ref Bucket
