name: deploy
on: [push,workflow_dispatch]
concurrency: 0
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Install Python Requirements
        shell: bash
        run: |
          cd ./stream_function
          pip install -r requirements.txt -t ./
          cd ./..

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: AWS CloudFormation Package
        shell: bash
        run: |
          aws cloudformation package \
            --template-file aws-cfstack.yaml \
            --output-template-file aws-cfstack_pkgd.yaml \
            --s3-bucket ${{ secrets.AWS_INFRA_BUCKET }} \
            --s3-prefix package/${{ secrets.AWS_STACK_NAME }}

      - name: AWS CloudFormation Deploy
        shell: bash
        run: |
          aws cloudformation deploy \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND \
            --no-fail-on-empty-changeset \
            --template-file aws-cfstack_pkgd.yaml \
            --s3-bucket ${{ secrets.AWS_INFRA_BUCKET }} \
            --s3-prefix package/${{ secrets.AWS_STACK_NAME }} \
            --stack-name ${{ secrets.AWS_STACK_NAME }} \
            --parameter-overrides Email=${{ secrets.EMAIL }}

      - name: Infra Artifacts
        shell: bash
        run: |
          aws cloudformation describe-stacks --stack-name ${{ secrets.AWS_STACK_NAME }} | \
            jq -r '.Stacks[0].Outputs' > aws-cfstack-outputs.json
          BUCKET_NAME=$(jq -r '.[] | select(.OutputKey == "BucketName") | .OutputValue' aws-cfstack-outputs.json)
          aws s3 cp ./streaming_job/ s3://$BUCKET_NAME/infra-artifacts/streaming_job/ --recursive